# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "664d98faa9f5f747da25aa32ef554211"
name = "smart-sticky"
handle = "smart-sticky"
application_url = "https://scenic-tv-atm-opt.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://scenic-tv-atm-opt.trycloudflare.com/auth/callback", "https://scenic-tv-atm-opt.trycloudflare.com/auth/shopify/callback", "https://scenic-tv-atm-opt.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
